'use strict';
const app=document.querySelector('#app');
const labels={dashboard:'Dashboard',violations:'My Violations',notifications:'Notifications',appeals:'My Appeals',profile:'My Profile',settings:'User Settings',report:'System Report'};
let me=null,page='dashboard',offset=0,generation=0,busy=false;
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=v=>v?new Date(v.replace(' ','T')+'Z').toLocaleString():'—';
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json','X-CSRF-Token':me?.csrf||''}:{},body:data?JSON.stringify(data):undefined});const result=await r.json();if(!r.ok){if(r.status===401&&me){me=null;login();}throw Error(result.error||'Request failed');}return result;}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',4500);}
function preferences(){document.documentElement.dataset.dark=!!me?.preferences?.dark_mode;document.querySelector('.layout')?.classList.toggle('compact',!!me?.preferences?.compact_sidebar);}
function login(){app.innerHTML=`<section class="login"><div class="card"><div class="seal">CBVMS</div><h1>Student Portal</h1><p class="muted">Your campus records, appeals, and updates in one place.</p><form id="login"><label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><p class="error" id="login-error" role="alert"></p><button class="btn">Sign in</button></form><p class="muted">Use the student account registered in CBVMS.</p></div></section>`;document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button');btn.disabled=true;try{me=await api('/api/login',Object.fromEntries(new FormData(e.target)));me=await api('/api/me');shell();}catch(err){document.querySelector('#login-error').textContent=err.message;}finally{btn.disabled=false;}};}
function shell(){app.innerHTML=`<div class="layout"><aside><h1>CBVMS</h1><p class="brand-note">Student Entrance Camera-based Uniform,<br>Grooming, Accessory Recognition and Evaluation</p><div class="identity">${escapeHTML(me.name)}</div><div class="eyebrow">STUDENT WORKSPACE</div><nav>${Object.entries(labels).map(([id,label])=>`<button data-page="${id}">${label}</button>`).join('')}</nav><button class="logout">↪ Logout</button></aside><main><header class="welcome"><div class="seal">CBVMS</div><div><h2>Welcome, ${escapeHTML(me.name)}.</h2><p>Your campus workspace is ready.</p></div><span class="tag">STUDENT</span></header><div class="heading"><h2 id="page-title"></h2><button class="btn secondary" id="refresh">Refresh</button></div><p class="muted" id="page-subtitle"></p><section id="content" aria-live="polite"></section></main></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;offset=0;load();});document.querySelector('.logout').onclick=async()=>{try{await api('/api/logout',{});me=null;login();}catch(e){toast(e.message);}};document.querySelector('#refresh').onclick=load;preferences();load();}
async function load(){const id=++generation;document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelector('#page-title').textContent=labels[page];document.querySelector('#page-subtitle').textContent=page==='settings'?'Customize your portal appearance and preferences.':'Connected to your campus records. Times are shown in your local timezone.';const content=document.querySelector('#content');content.innerHTML='<div class="card muted">Loading your records…</div>';try{const data=await api(`/api/page?page=${page}&offset=${offset}`);if(id!==generation)return;render(data);}catch(e){if(id===generation&&me)content.innerHTML=`<div class="card error">${escapeHTML(e.message)} <button class="btn secondary" id="retry">Try again</button></div>`;document.querySelector('#retry')?.addEventListener('click',load);}}
function violations(rows){return rows.map(r=>`<article class="card"><div class="record-head"><h3>${escapeHTML(r.violation_label||r.violation_type)} <small class="muted">#${r.id}</small></h3><span class="pill">${escapeHTML(r.appeal_status||r.status)}</span></div><p class="muted">Detected ${time(r.timestamp)} · ${escapeHTML(r.semester_name)} ${escapeHTML(r.school_year)}</p><p class="muted">Appeal deadline: ${time(r.appeal_deadline)}</p><p>${r.can_appeal?'You may appeal this record with an explanation and picture.':escapeHTML(r.appeal_eligibility_reason||'View your appeal status for this record.')}</p><div class="actions"><button class="btn secondary" data-evidence="${r.id}">View detection picture</button>${r.can_appeal?`<button class="btn" data-appeal="${r.id}">Submit appeal</button>`:''}</div><div id="evidence-${r.id}"></div><div id="appeal-${r.id}"></div></article>`).join('')||'<div class="card empty">No violations to show.</div>';}
function render(d){const c=document.querySelector('#content');let html='';
if(page==='dashboard'){const counts=d._violation_counts||{};html=`<div class="stats">${[['Pending records',counts.pending||0],['Confirmed records',counts.confirmed||0],['Pending appeals',d._pending_appeals||0]].map(([title,n])=>`<div class="card"><div class="muted">${title}</div><div class="number">${n}</div></div>`).join('')}</div><div class="card"><h3>Current semester standing</h3>${(d._strike_summary||[]).map(s=>`<div class="row"><strong>${escapeHTML(s.violation_label)}</strong><span>${s.active_count} / ${s.strike_limit} strikes</span></div>`).join('')}<p class="muted">${d._active_suspension?`Suspended until ${time(d._active_suspension.ends_at)}. ${escapeHTML(d._active_suspension.reason)}`:'No active suspension.'}</p></div><h3>Recent violations</h3>${violations(d._violations||[])}`;}
if(page==='violations')html=violations(d._violations||[]);
if(page==='notifications')html=`<button class="btn secondary" id="read-all">Mark all as read</button>`+(d._notifications||[]).map(n=>`<article class="card"><div class="record-head"><h3>${escapeHTML(n.title)}</h3><span class="pill">${n.is_read?'Read':'Unread'}</span></div><p>${escapeHTML(n.message)}</p><p class="muted">${time(n.created_at)}</p>${!n.is_read?`<button class="btn secondary" data-read="${n.id}">Mark as read</button>`:''}</article>`).join('');
if(page==='appeals')html=(d._appeals||[]).map(a=>`<article class="card"><div class="record-head"><h3>Appeal for violation #${a.violation_id}</h3><span class="pill">${escapeHTML(a.status)}</span></div><p>${escapeHTML(a.reason)}</p><p class="muted">Submitted ${time(a.submitted_at)}</p>${a.admin_notes?`<p><strong>Admin response:</strong> ${escapeHTML(a.admin_notes)}</p>`:''}</article>`).join('')||'<div class="card empty">No appeals submitted.</div>';
if(page==='settings')html=`<div class="card"><h3>Appearance</h3>${toggle('dark_mode','Dark mode','Use a darker color scheme across the portal')}${toggle('compact_sidebar','Compact sidebar','Reduce sidebar spacing for more workspace')}</div>`;
if(page==='profile'){const s=d._student||{};html=`<div class="card"><h3>Student details</h3><dl class="details">${['student_id','name','course','year_and_section','email','student_status'].map(k=>`<dt>${escapeHTML(k.replaceAll('_',' '))}</dt><dd>${escapeHTML(s[k]||'—')}</dd>`).join('')}</dl></div><div class="card"><h3>Display name</h3><form id="profile"><label>Name<input name="name" value="${escapeHTML(s.name)}" maxlength="120" required></label><button class="btn">Save name</button></form></div><div class="card"><h3>Change password</h3><form id="password"><label>Username<input name="username" autocomplete="username" required></label><label>Current password<input name="current_password" type="password" autocomplete="current-password" required></label><label>New password<input name="password" type="password" minlength="6" autocomplete="new-password" required></label><button class="btn">Change password</button></form></div>`;}
if(page==='report')html=`<div class="card"><h3>Send a report to the administrator</h3><form id="report"><label>Title<input name="title" maxlength="200" required></label><label>Category<select name="category">${['System Bug','Account Issue','Violation Dispute','Other'].map(v=>`<option>${v}</option>`).join('')}</select></label><label>Description<textarea name="description" maxlength="10000" required></textarea></label><button class="btn">Submit report</button></form></div>`;
if(['violations','notifications','appeals'].includes(page))html+=`<div class="pager">${offset?'<button class="btn secondary" id="previous">Previous</button>':''}${d._has_more?'<button class="btn secondary" id="next">Next</button>':''}</div>`;
c.innerHTML=html;bind();}
function toggle(key,title,description){return `<label class="row"><span><strong>${title}</strong><p class="muted">${description}</p></span><input type="checkbox" data-pref="${key}" ${me.preferences?.[key]?'checked':''}></label>`;}
function bind(){document.querySelector('#next')?.addEventListener('click',()=>{offset+=10;load();});document.querySelector('#previous')?.addEventListener('click',()=>{offset=Math.max(0,offset-10);load();});document.querySelectorAll('[data-pref]').forEach(el=>el.onchange=async()=>{try{me.preferences=await api('/api/preferences',{[el.dataset.pref]:el.checked});preferences();}catch(e){el.checked=!el.checked;toast(e.message);}});document.querySelectorAll('[data-read]').forEach(el=>el.onclick=()=>action('/api/notifications/read',{id:Number(el.dataset.read)}));document.querySelector('#read-all')?.addEventListener('click',()=>action('/api/notifications/read',{}));document.querySelectorAll('[data-evidence]').forEach(el=>el.onclick=async()=>{try{const r=await fetch(`/api/evidence?id=${el.dataset.evidence}`);if(!r.ok)throw Error('Picture unavailable.');const url=URL.createObjectURL(await r.blob());const img=document.createElement('img');img.className='evidence';img.alt='Original detection evidence';img.onload=()=>URL.revokeObjectURL(url);img.src=url;document.querySelector(`#evidence-${el.dataset.evidence}`).replaceChildren(img);}catch(e){toast(e.message);}});document.querySelectorAll('[data-appeal]').forEach(el=>el.onclick=()=>appealForm(Number(el.dataset.appeal)));for(const name of ['report','profile','password']){const f=document.querySelector('#'+name);if(f)f.onsubmit=async e=>{e.preventDefault();await action('/api/'+(name==='report'?'reports':name),Object.fromEntries(new FormData(f)),name==='profile');};}}
async function action(path,data,rebuild=false){if(busy)return;busy=true;try{await api(path,data);toast('Saved successfully.');if(rebuild){me=await api('/api/me');shell();}else await load();}catch(e){toast(e.message);}finally{busy=false;}}
function appealForm(id){const host=document.querySelector(`#appeal-${id}`);host.innerHTML=`<form class="card"><h3>Appeal violation #${id}</h3><label>Explanation<textarea name="reason" required></textarea></label><label>Supporting picture (JPG, PNG, BMP; up to 10 MB)<input name="picture" type="file" accept=".jpg,.jpeg,.png,.bmp" required></label><button class="btn">Submit appeal</button></form>`;host.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.target,btn=f.querySelector('button'),file=f.elements.picture.files[0];if(!file||file.size>10*1024*1024){toast('Choose a picture up to 10 MB.');return;}btn.disabled=true;try{const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});await api('/api/appeals',{violation_id:id,reason:f.elements.reason.value,filename:file.name,file:encoded});toast('Appeal submitted to the administrator.');await load();}catch(e){toast(e.message);btn.disabled=false;}};}
async function start(){try{me=await api('/api/me');shell();}catch{login();}}
start();
setInterval(()=>{if(me&&['dashboard','violations','notifications','appeals'].includes(page)&&!document.querySelector('form')&&!busy)load();},30000);
